// <auto-generated />
using System;
using Grovetracks.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Grovetracks.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Grovetracks.DataAccess.Entities.DoodleEngagement", b =>
                {
                    b.Property<string>("KeyId")
                        .HasColumnType("text")
                        .HasColumnName("key_id");

                    b.Property<DateTime>("EngagedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("engaged_at");

                    b.Property<double>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.HasKey("KeyId");

                    b.ToTable("doodle_engagements", (string)null);
                });

            modelBuilder.Entity("Grovetracks.DataAccess.Entities.QuickdrawDoodle", b =>
                {
                    b.Property<string>("KeyId")
                        .HasColumnType("text")
                        .HasColumnName("key_id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("country_code");

                    b.Property<string>("DrawingReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("drawing_reference");

                    b.Property<bool>("Recognized")
                        .HasColumnType("boolean")
                        .HasColumnName("recognized");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("word");

                    b.HasKey("KeyId");

                    b.HasIndex("Word");

                    b.ToTable("quickdraw_doodles", (string)null);
                });

            modelBuilder.Entity("Grovetracks.DataAccess.Entities.QuickdrawSimpleDoodle", b =>
                {
                    b.Property<string>("KeyId")
                        .HasColumnType("text")
                        .HasColumnName("key_id");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("country_code");

                    b.Property<string>("Drawing")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("drawing");

                    b.Property<bool>("Recognized")
                        .HasColumnType("boolean")
                        .HasColumnName("recognized");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("word");

                    b.HasKey("KeyId");

                    b.HasIndex("Word");

                    b.ToTable("quickdraw_simple_doodles", (string)null);
                });

            modelBuilder.Entity("Grovetracks.DataAccess.Entities.SeedComposition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompositionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("composition_json");

                    b.Property<DateTime>("CuratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("curated_at");

                    b.Property<string>("GenerationMethod")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("generation_method");

                    b.Property<double>("QualityScore")
                        .HasColumnType("double precision")
                        .HasColumnName("quality_score");

                    b.Property<string>("SourceCompositionIds")
                        .HasColumnType("text")
                        .HasColumnName("source_composition_ids");

                    b.Property<string>("SourceKeyId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source_key_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("curated")
                        .HasColumnName("source_type");

                    b.Property<int>("StrokeCount")
                        .HasColumnType("integer")
                        .HasColumnName("stroke_count");

                    b.Property<int>("TotalPointCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_point_count");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("word");

                    b.HasKey("Id");

                    b.HasIndex("QualityScore");

                    b.HasIndex("SourceType");

                    b.HasIndex("Word");

                    b.ToTable("seed_compositions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
